[tool.poetry]
name = "nonebot-plugin-clovers"
version = "0.1.2"
description = ""
authors = ["KarisAya <1048827424@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
nonebot2 = "^2.2.1"
nonebot-adapter-onebot = "^2.4.3"
nonebot-adapter-qq = "^1.4.3"
clovers = "^0.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
