[tool.poetry]
name = "nonebot-plugin-clovers"
version = "0.1.2r2"
description = ""
authors = ["KarisAya <1048827424@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
nonebot2 = "^2.2.1"
nonebot-adapter-onebot = {version = "^2.4.3", optional = true}
nonebot-adapter-qq = {version = "^1.4.3", optional = true}

[tool.poetry.extras]
onebot = ["nonebot-adapter-onebot",]
qq = ["nonebot-adapter-qq",]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
